// SPDX-License-Identifier: GPL-3.0-or-later
#ifndef FORDLINK_OBD2_H
#define FORDLINK_OBD2_H

#include "link/obd2.h"
#include "link/dtc_knowledge.h"

typedef LinkObd2Result FordlinkObd2Result;
typedef LinkObd2Unit FordlinkObd2Unit;
typedef LinkObd2PidDefinition FordlinkObd2PidDefinition;
typedef LinkObd2DecodedPid FordlinkObd2DecodedPid;
typedef LinkObd2DtcKind FordlinkObd2DtcKind;
typedef LinkObd2DtcList FordlinkObd2DtcList;
typedef LinkObd2PidSet FordlinkObd2PidSet;
typedef LinkDtcKnowledge FordlinkDtcKnowledge;

#define FORDLINK_OBD2_RESULT_OK LINK_OBD2_RESULT_OK
#define FORDLINK_OBD2_DTC_STORED LINK_OBD2_DTC_STORED
#define FORDLINK_OBD2_DTC_PENDING LINK_OBD2_DTC_PENDING
#define FORDLINK_OBD2_DTC_PERMANENT LINK_OBD2_DTC_PERMANENT

#define fordlink_obd2_pid_definition_count link_obd2_pid_definition_count
#define fordlink_obd2_pid_definition_at link_obd2_pid_definition_at
#define fordlink_obd2_mode01_assigned_count link_obd2_mode01_assigned_count
#define fordlink_obd2_build_live_pid_request link_obd2_build_live_pid_request
#define fordlink_obd2_build_freeze_pid_request link_obd2_build_freeze_pid_request
#define fordlink_obd2_build_supported_pid_request link_obd2_build_supported_pid_request
#define fordlink_obd2_build_vin_request link_obd2_build_vin_request
#define fordlink_obd2_build_dtc_request link_obd2_build_dtc_request
#define fordlink_obd2_decode_pid_payload link_obd2_decode_pid_payload
#define fordlink_obd2_decode_dtc_pair link_obd2_decode_dtc_pair
#define fordlink_obd2_obdonuds_pid_to_did link_obd2_obdonuds_pid_to_did
#define fordlink_dtc_resolve link_dtc_resolve

#endif
